#ifndef BLT_STREAMING_PATCHER_H
#define BLT_STREAMING_PATCHER_H

#include "blt_common.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct BltStreamingPatcher BltStreamingPatcher;

/**
 * Create a stateful streaming patcher for generation hot-path inference.
 *
 * @param theta_r Monotonic entropy jump threshold
 * @param max_patch_size Maximum patch size before forcing a boundary (e.g. 32, or 0 if unlimited)
 * @param reset_on_newline Reset entropy context when byte is '\n'
 * @param doc_boundary_token Document boundary token value (e.g. 256)
 * @return Pointer to opaque patcher instance, or NULL on failure
 */
BLT_API BltStreamingPatcher* blt_streaming_patcher_create(
    float theta_r,
    int32_t max_patch_size,
    int32_t reset_on_newline,
    int32_t doc_boundary_token
);

/**
 * Feed a newly generated byte and its entropy estimate.
 *
 * @param patcher Patcher instance
 * @param byte_val Byte value generated (0-255, or special tokens)
 * @param entropy_val Entropy value H(x_t) computed by entropy model
 * @return 1 if this byte begins a new patch, 0 if it continues current patch, < 0 on error
 */
BLT_API int32_t blt_streaming_patcher_feed(
    BltStreamingPatcher* patcher,
    int32_t byte_val,
    float entropy_val
);

/**
 * Reset streaming patcher state for a new generation sequence.
 */
BLT_API void blt_streaming_patcher_reset(BltStreamingPatcher* patcher);

/**
 * Get current patch length (bytes accumulated in current patch).
 */
BLT_API int32_t blt_streaming_patcher_get_current_patch_len(const BltStreamingPatcher* patcher);

/**
 * Destroy the streaming patcher instance and free memory.
 */
BLT_API void blt_streaming_patcher_destroy(BltStreamingPatcher* patcher);

#ifdef __cplusplus
}
#endif

#endif // BLT_STREAMING_PATCHER_H
